### ISSUE TITLE
Username not an Email-Address

### ISSUE THREAD

**Issue by as149** [LeonardoRM/owncloud-roundcube#4]
Hi,
all my Owncloud-User have Usernames without "@domainname".
So I can't open the Roundcube-App. It apperas the error message "Username 'USERNAME' is not an email address."
The older Roundcube App by hypery2k has Usersettings, where you can set a different Username for Roundcube.
Owncloud itself have no option to change Usernames. So I would have to recreate all users.
Is it possible to implement Usersettings again?
Greetings
stizi

**Comment by LeonardoRM** [comment]
Hi!
Right now the OC login needs to be an email address, and with the same password it logs into RC.
OC provides the user with an optional _email_ field (through personal config).
Do your users log into RC with _that email_ and the same OC password?
Or RC credentials are a completely different set?

**Comment by as149** [comment]
Hi,
til now all users login with username without "@domain".
Even I login with my email-address, Roundcube-App says still that my Username isn't a email address.
So Roundcube App doesn't use the login I actually use, but the login saved in database.

**Comment by LeonardoRM** [comment]
That's right, RC app uses OC uid, which is your login (without the domain: johndoe), that's why it doesn't log in.
I need to setup a test environment first, but I'll add it anyway.

So, the case to implement would be like this:
- OC UID is not an email address (e.g. johndoe).
- OC user has set up an email address through personal settings (john.doe@example.com).
- RC app could login a user using: OC user's email field and OC password for UID johndoe.
- Note: No database with custom credentials for now.

**Comment by as149** [comment]
Hi,
It Sounds good.
That's what I'm looking vor.

**Comment by flionet89** [comment]
You can take data from the **owncloud** database table **os_accounts** column **email**.

**Comment by flionet89** [comment]
![image](https://user-images.githubusercontent.com/54624114/64309381-21d73a80-cfbe-11e9-9c6c-fe8353897f76.png)

**Comment by flionet89** [comment]
YOU can use the function **getEMailAddress**

**Comment by flionet89** [comment]
What is needed to implement this project?

**Comment by yawamdam** [comment]
I have OC (RC , and other) users from LDAP (AD) -> only username auth.

**Comment by as149** [comment]
Any update on this?

**Comment by LeonardoRM** [comment]
@as149 @flionet89 
Here's a PR with the code to be tested for this feature.
#8 FEAT/4-email-as-username

Could you please test it? If it passes, I can merge and release a new version.
- Create two users:
  - UID: **email1@domain.com** ; the OC password must be the same that the email has.
  - UID: **user2**; set user email as email2@domain.com ; the OC password must be the same that the email has.
- Login with both users and check if both can open the RC app and see the inbox.
- If that succeeds, then test passes.

**Comment by flionet89** [comment]
I tried to use the new version. It does not work. If login and email are the same then it works. If different, then no.

**Comment by LeonardoRM** [comment]
Just in case, when using the email user, the login to OC (UID) can't be an email address, because if it is, it'll use it.
Also, could you paste the log messages please?

**Comment by flionet89** [comment]
Hi. 
LOG

{"reqId":"9u04rwBm9JFHgKAC6QLO","level":2,"time":"2020-04-02T06:17:15+00:00","remoteAddr":"192.168.3.9","user":"borodinryu","app":"roundcube","method":"GET","url":"\/apps\/roundcube\/","message":"OCA\\RoundCube\\BackLogin::sendRequest: Opening url '?_task=login' failed with '<url> malformed'"}
{"reqId":"9u04rwBm9JFHgKAC6QLO","level":3,"time":"2020-04-02T06:17:15+00:00","remoteAddr":"192.168.3.9","user":"borodinryu","app":"roundcube","method":"GET","url":"\/apps\/roundcube\/","message":"OCA\\RoundCube\\BackLogin::login: Could not get login page."}

**Comment by LeonardoRM** [comment]
That error is related to configuration:
Did you set at least the default RC path? e.g.: roundcube1/

**Comment by flionet89** [comment]
![изображение](https://user-images.githubusercontent.com/54624114/78520276-cd13d080-77e7-11ea-958c-adbffb0a8d87.png)

**Comment by flionet89** [comment]
I use roundcube 1.4.1
Proxying is configured on nginx.
Mail site open.
![изображение](https://user-images.githubusercontent.com/54624114/78520617-0c8eec80-77e9-11ea-8a64-c7c07eeb6c69.png)

**Comment by flionet89** [comment]
Unfortunately does not work. It works according to the rules of the main plugin.
If someone has earned write. Maybe I'm doing something wrong.

**Comment by flionet89** [comment]
Hello. After the modification, the script started working.

**Comment by LeonardoRM** [comment]
PR was merged.
