### ISSUE TITLE
The plugin does not work with the OwnCloud 10.2.1 and Roundcube 1.3.7. How to fix this?

### ISSUE THREAD

**Issue by flionet89** [LeonardoRM/owncloud-roundcube#5]
Hi. The plugin does not work with the OwnCloud 10.2.1 and Roundcube 1.3.7. How to fix this?
![error1](https://user-images.githubusercontent.com/54624114/63846756-3ad46000-c9ae-11e9-94d9-7d20a3597402.jpg)
![error2](https://user-images.githubusercontent.com/54624114/63846764-41fb6e00-c9ae-11e9-86e7-26a485808839.jpg)

**Comment by flionet89** [comment]
AutoLogin is not work.

**Comment by LeonardoRM** [comment]
Hi!
Did you try setting the RC path to something relative to owncloud server? For example: "roundcube/".
The full path would then be `https://cloudx.corp....kz/owncloud/roundcube` in your case, and it should point to RC installation.

**Comment by flionet89** [comment]
Yes. I used different options. The result is the same.

**Comment by flionet89** [comment]
Installed Roundcube 1.3.10. Also does not work.

**Comment by flionet89** [comment]
I use PHP7.2 and 10.4.7-MariaDB. Is this possible?

**Comment by flionet89** [comment]
{"reqId":"XWeJW3@p-39XAjjroKtORwAAAAk","level":2,"time":"2019-08-29T08:14:19+00:00","remoteAddr":"192.168.3.9","user":"                                                                    borodinryu@corp.common.kz","app":"roundcube","method":"GET","url":"\/owncloud\/index.php\/apps\/roundcube\/","message":                                                                    "OCA\\RoundCube\\BackLogin::sendRequest: Disabling SSL verification."}
{"reqId":"XWeJW3@p-39XAjjroKtORwAAAAk","level":3,"time":"2019-08-29T08:14:25+00:00","remoteAddr":"192.168.3.9","user":"                                                                    borodinryu@corp.common.kz","app":"PHP","method":"GET","url":"\/owncloud\/index.php\/apps\/roundcube\/","message":"Undef                                                                    ined index: set-cookie at \/usr\/share\/owncloud\/apps\/roundcube\/lib\/BackLogin.php#76"}
{"reqId":"XWeJW3@p-39XAjjroKtORwAAAAk","level":3,"time":"2019-08-29T08:14:25+00:00","remoteAddr":"192.168.3.9","user":"                                                                    borodinryu@corp.common.kz","app":"PHP","method":"GET","url":"\/owncloud\/index.php\/apps\/roundcube\/","message":"Undef                                                                    ined index: _token at \/usr\/share\/owncloud\/apps\/roundcube\/lib\/BackLogin.php#83"}
{"reqId":"XWeJW3@p-39XAjjroKtORwAAAAk","level":3,"time":"2019-08-29T08:14:25+00:00","remoteAddr":"192.168.3.9","user":"                                                                    borodinryu@corp.common.kz","app":"PHP","method":"GET","url":"\/owncloud\/index.php\/apps\/roundcube\/","message":"Undef                                                                    ined index: _timezone at \/usr\/share\/owncloud\/apps\/roundcube\/lib\/BackLogin.php#86"}
{"reqId":"XWeJW3@p-39XAjjroKtORwAAAAk","level":3,"time":"2019-08-29T08:14:25+00:00","remoteAddr":"192.168.3.9","user":"                                                                    borodinryu@corp.common.kz","app":"PHP","method":"GET","url":"\/owncloud\/index.php\/apps\/roundcube\/","message":"Undef                                                                    ined index: _url at \/usr\/share\/owncloud\/apps\/roundcube\/lib\/BackLogin.php#87"}
{"reqId":"XWeJW3@p-39XAjjroKtORwAAAAk","level":2,"time":"2019-08-29T08:14:25+00:00","remoteAddr":"192.168.3.9","user":"                                                                    borodinryu@corp.common.kz","app":"roundcube","method":"GET","url":"\/owncloud\/index.php\/apps\/roundcube\/","message":                                                                    "OCA\\RoundCube\\BackLogin::sendRequest: Disabling SSL verification."}
{"reqId":"XWeJW3@p-39XAjjroKtORwAAAAk","level":3,"time":"2019-08-29T08:14:25+00:00","remoteAddr":"192.168.3.9","user":"                                                                    borodinryu@corp.common.kz","app":"PHP","method":"GET","url":"\/owncloud\/index.php\/apps\/roundcube\/","message":"Undef                                                                    ined index: set-cookie at \/usr\/share\/owncloud\/apps\/roundcube\/lib\/BackLogin.php#98"}

**Comment by LeonardoRM** [comment]
Can you enable the setting SSL validation and try it or your RC server doesn't support SSL?

**Comment by flionet89** [comment]
Everything is working. Thanks.
