### ISSUE TITLE
 The plugin does not work with Roundcube 1.4 (elastic skin)

### ISSUE THREAD

**Issue by flionet89** [LeonardoRM/owncloud-roundcube#6]
Hi. I tried to open roundcube 1.4 but got an error. 

> Unable to login into roundcube. There are login errors. Relogin to ownCloud. Relogin to ownCloud.

**Comment by flionet89** [comment]
Log roundcube
{"reqId":"JQsCqDpvTBfSEuUXJVmb","level":0,"time":"2019-09-18T11:31:49+06:00","remoteAddr":"192.168.3.9","user":"borodinryu@on.kz","app":"roundcube","method":"GET","url":"\/apps\/roundcube\/","message":"OCA\\RoundCube\\Crypto::privateDecrypt: Starting decryption."}
{"reqId":"JQsCqDpvTBfSEuUXJVmb","level":0,"time":"2019-09-18T11:31:49+06:00","remoteAddr":"192.168.3.9","user":"borodinryu@on.kz","app":"roundcube","method":"GET","url":"\/apps\/roundcube\/","message":"OCA\\RoundCube\\BackLogin::sendRequest: URL: 'https:\/\/cloudx.corp.common.kz\/roundcube\/?_task=login'."}
{"reqId":"JQsCqDpvTBfSEuUXJVmb","level":0,"time":"2019-09-18T11:31:54+06:00","remoteAddr":"192.168.3.9","user":"borodinryu@on.kz","app":"roundcube","method":"GET","url":"\/apps\/roundcube\/","message":"OCA\\RoundCube\\BackLogin::sendRequest: Got the following HTTP Status Code: (401) 0: "}
{"reqId":"JQsCqDpvTBfSEuUXJVmb","level":2,"time":"2019-09-18T11:31:54+06:00","remoteAddr":"192.168.3.9","user":"borodinryu@on.kz","app":"roundcube","method":"GET","url":"\/apps\/roundcube\/","message":"OCA\\RoundCube\\BackLogin::sendRequest: Opening url 'https:\/\/cloudx.corp.common.kz\/roundcube\/?_task=login' failed with ''"}
{"reqId":"JQsCqDpvTBfSEuUXJVmb","level":3,"time":"2019-09-18T11:31:54+06:00","remoteAddr":"192.168.3.9","user":"borodinryu@on.kz","app":"roundcube","method":"GET","url":"\/apps\/roundcube\/","message":"OCA\\RoundCube\\BackLogin::login: Could not get login page."}

**Comment by flionet89** [comment]
Roundcube 1.3.10 is opening.

**Comment by LeonardoRM** [comment]
Let's wait (at least) until RoundCube 1.4 is released, right now is release candidate 2. Then, please try again.

**Comment by flionet89** [comment]
Hi.  RoundCube 1.4 is released.

**Comment by flionet89** [comment]
:"GET","url":"/apps/roundcube/","message":"OCA\RoundCube\BackLogin::sendRequest: Opening url 'https://on.kz/roundcube/?_task=login' failed with ''"}

**Comment by flionet89** [comment]
Hi. RoundCube 1.4.1 good working with plugin.
