### ISSUE TITLE
REQ: Nextcloud 19 compatibility

### ISSUE THREAD

**Issue by nextgen-networks** [LeonardoRM/owncloud-roundcube#9]
Hallo @LeonardoRM and veryone elst who'is interested in!

Is there any possibility to get this plugin working for Nextcloud 19?
Tried to do so in the past but Admin-Settings create a NC error.
I was not able to solve this with my very limited understanding for web-coding - but maybe you are?

Would be great to have Roundcobe integrated in NC also!

Thanks!

**Comment by flionet89** [comment]
Hey! I managed to adapt the plugin for NextCloud 21. If you need it, write to me on flinet@bk.ru.

**Comment by flionet89** [comment]
https://github.com/flionet89/Nextcloud-roundcube for nextcloud

**Comment by nextgen-networks** [comment]
Several forks & versions for NC 2x have been made available.
Big thanks to everyone who put effort in this!
